import localFont from "next/font/local";
import { Dela_Gothic_One, Montserrat } from "next/font/google";
import type { Metadata, Viewport } from "next";
import "./globals.css";
import PublicLayout from "@/components/PublicLayout/publicLayout";

const montserrat = Montserrat({
  subsets: ['latin'],
})

const delaGothicOne = Dela_Gothic_One({
  variable: "--font-dela-gothic-one",
  subsets: ["latin"],
  weight: ["400"],
});

const bimbo = localFont({
  src: [
    {
      path: "./fonts/bimbolight.woff",
      weight: '100',
      style: 'normal'
    },
    {
      path: "./fonts/bimboregular.woff",
      weight: '400',
      style: 'normal'
    },
    {
      path: "./fonts/bimbosemibold.woff",
      weight: '600',
      style: 'normal'
    },
    {
      path: "./fonts/bimbobold.woff",
      weight: '700',
      style: 'normal'
    }
  ],
  variable: "--font-bimbo",
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  openGraph: {
    title: "Portfolio",
    description: "Generated by create next app",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Portfolio",
      },
    ],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  interactiveWidget: "resizes-content",
  themeColor: "#FFFFFF",
}

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={`${delaGothicOne.variable} ${montserrat.className} ${bimbo.variable} antialiased select-none`}>
        <PublicLayout>{children}</PublicLayout>
      </body>
    </html>
  );
}
